ALTER TABLE "User" ADD COLUMN "xpTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "weeklyXP" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "seasonalXP" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "level" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "lastMessageAt" TIMESTAMP;
ALTER TABLE "User" ADD COLUMN "streakDays" INTEGER NOT NULL DEFAULT 0;
