CREATE TABLE IF NOT EXISTS central_bank (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    totalBalance INTEGER DEFAULT 0,
    lastUpdated TEXT DEFAULT CURRENT_TIMESTAMP,
    createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
);
